/*
 * File:     cse13s_random.h
 * Author:   Dr. Kerry Veenstra
 * Purpose:  Header file for cse13s_random.c
 */

/*
 * DO NOT EDIT THIS FILE
 */

void cse13s_random_seed(unsigned seed);
int cse13s_random(void);
