/*
 * File:     names.h
 * Purpose:  Provide player names for CSE 13S, Fall 2023, Assignment 1
 */

/*
 * DO NOT EDIT THIS FILE
 */

const char *player_name[] = {
    "Ada Lovelace", // 1815-1852.  Wrote the first algorithm for a
    // computer.

    "Margaret Hamilton", // 1936-.  While in her 20s, lead the team that
    // wrote and tested the Apollo moon program's
    // on-board flight software. Invented the term
    // "software engineering".

    "Katherine Johnson", // 1918-2020.  Mathematician who hand-calculated
    // trajectories for crewed spaceflights.

    "Joy Buolamwini", // ~1989-.  MIT computer scientist who works to
    // challenge racial and gender bias in AI-based
    // decision software.

    "Grace Hopper", // 1906-1992.  Mathematician and computer
    // scientist who made the first
    // machine-independent computer language.

    "Adele Goldberg", // 1945-.  Managed the team at Xerox that
    // developed object-oriented programming and
    // graphical user interfaces.

    "Annie Easley", // 1933-2011.  NASA computer scientist and
    // mathematician who developed algorithms that
    // analyze various power technologies.

    "Jeannette Wing", // 1956-.  Led many research projects as a
    // university professor and as a vice president
    // at Microsoft Research.

    "Mary Kenneth Keller", // 1913-1985.  First person to earn a Ph.D. in
    // computer science in the United States.

    "Megan Smith", // 1964-.  Vice president at Google and 3rd
    // Chief Technology Officer of the United States.

    "Radia Perlman" // 1958-.  Computer programmer and network
    // engineer who invented many network protocols
    // include the Spanning Tree Protocol used by
    // network bridges.
};

#define MAX_PLAYERS ((int) (sizeof(player_name) / sizeof(player_name[0])))
